### ISSUE TITLE
Bug with lists

### ISSUE THREAD

**Issue by bbasics** [stefankoegl/python-json-patch#101]
```
import jsonpatch
jsonpatch.make_patch(['1', '2', '3', '4'], ['4', '3', '1', '2', '2'])
```
gives:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/jsonpatch.py", line 494, in apply
    value = subobj[part]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test.py", line 3, in <module>
    jsonpatch.make_patch(['1', '2', '3', '4'], ['4', '3', '1', '2', '2'])
  File "/usr/lib/python3/dist-packages/jsonpatch.py", line 178, in make_patch
    new = patch.apply(src)
  File "/usr/lib/python3/dist-packages/jsonpatch.py", line 360, in apply
    obj = operation.apply(obj)
  File "/usr/lib/python3/dist-packages/jsonpatch.py", line 496, in apply
    raise JsonPatchConflict(str(ex))
jsonpatch.JsonPatchConflict: list index out of range
```
I use bionic ubuntu package (version 1.19)

Best regards

**Comment by Alanscut** [comment]
it seems works fine now.
