### ISSUE TITLE
TypeError on replace with list index '-'

### ISSUE THREAD

**Issue by twbecker** [stefankoegl/python-json-patch#102]
Best shown with an example:
```bash
$ cat test.json 
{"foo": [0, 1, 2]}

$ echo '[{"op": "replace", "path": "/foo/-", "value": "3"}]' | jsonpatch ./test.json
Traceback (most recent call last):
  File "venv/bin/jsonpatch", line 106, in <module>
    main()
  File "venv/bin/jsonpatch", line 31, in main
    patch_files()
  File "venv/bin/jsonpatch", line 41, in patch_files
    result = jsonpatch.apply_patch(doc, patch)
  File "venv/lib/python3.6/site-packages/jsonpatch.py", line 143, in apply_patch
    return patch.apply(doc, in_place)
  File "venv/lib/python3.6/site-packages/jsonpatch.py", line 312, in apply
    obj = operation.apply(obj)
  File "venv/lib/python3.6/site-packages/jsonpatch.py", line 477, in apply
    if part > len(subobj) or part < 0:
TypeError: '>' not supported between instances of 'str' and 'int'
```

I fully agree that replace with '-' doesn't make sense, but it would be preferable IMO for this to raise `InvalidJsonPatch` or `JsonPatchConflict` than `TypeError`. Indeed this was the behavior under Python 2:
```bash
$  echo '[{"op": "replace", "path": "/foo/-", "value": "3"}]' | jsonpatch ~/projects/ffs/ffs-server/src/test/robotframework/test.json
Traceback (most recent call last):
  File "venv2/bin/jsonpatch", line 106, in <module>
    main()
  File "venv2/bin/jsonpatch", line 31, in main
    patch_files()
  File "venv2/bin/jsonpatch", line 41, in patch_files
    result = jsonpatch.apply_patch(doc, patch)
  File "venv2/local/lib/python2.7/site-packages/jsonpatch.py", line 143, in apply_patch
    return patch.apply(doc, in_place)
  File "venv2/local/lib/python2.7/site-packages/jsonpatch.py", line 312, in apply
    obj = operation.apply(obj)
  File "venv2/local/lib/python2.7/site-packages/jsonpatch.py", line 476, in apply
    raise JsonPatchConflict("can't replace outside of list")
jsonpatch.JsonPatchConflict: can't replace outside of list
```

**Comment by Alanscut** [comment]
this error message confused me, too. I fixed this case in #113, do you think it makes sense?
