### ISSUE TITLE
test test_make_patch_unicode fails in -1.11 under py2.7, pypy

### ISSUE THREAD

**Issue by idella** [stefankoegl/python-json-patch#39]
```bash
..............................................E....................
======================================================================
ERROR: test_make_patch_unicode (__main__.MakePatchTestCase)
Test if unicode keys and values are handled correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 358, in test_make_patch_unicode
    patch = jsonpatch.make_patch(src, dst)
  File "/mnt/gen2/TmpDir/portage/dev-python/jsonpatch-1.11/work/jsonpatch-1.11/jsonpatch.py", line 171, in make_patch
    return JsonPatch.from_diff(src, dst)
  File "/mnt/gen2/TmpDir/portage/dev-python/jsonpatch-1.11/work/jsonpatch-1.11/jsonpatch.py", line 322, in from_diff
    return cls(list(compare_values([], src, dst)))
  File "/mnt/gen2/TmpDir/portage/dev-python/jsonpatch-1.11/work/jsonpatch-1.11/jsonpatch.py", line 293, in compare_values
    for operation in compare_dicts(path, value, other):
  File "/mnt/gen2/TmpDir/portage/dev-python/jsonpatch-1.11/work/jsonpatch-1.11/jsonpatch.py", line 314, in compare_dicts
    ptr = JsonPointer.from_parts(path + [key])
  File "/usr/lib64/python2.7/site-packages/jsonpointer.py", line 291, in from_parts
    parts = [str(part) for part in parts]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xee' in position 0: ordinal not in range(128)

----------------------------------------------------------------------
Ran 67 tests in 0.025s

FAILED (errors=1)
```
ditto pypy.
Do you require any further information?

**Comment by idella** [comment]
cancel close was using prior jsonpointer
