### ISSUE TITLE
Issue generating Array diff tree

### ISSUE THREAD

**Issue by neoshrew** [stefankoegl/python-json-patch#40]
(I did look at issue #30 , but that was after a successful creation of a patch. Apologies if I've misunderstood and it is the same issue)

I've been starting at this, and it looks like the issue lies in _split_by_common_seq

Take the following example
```python
import jsonpatch

src = [8, 7, 2, 1, 0, 9, 4, 3, 5, 6]
dest = [7, 2, 1, 0, 9, 4, 3, 6, 5, 8]

patch = jsonpatch.make_patch(src, dest)
```

When run, it produces the following error
```
$ python tmp.py 
Traceback (most recent call last):
  File "tmp.py", line 6, in <module>
    patch = jsonpatch.make_patch(src, dest)
  File "/space/TMP/crap/python-json-patch/jsonpatch.py", line 171, in make_patch
    return JsonPatch.from_diff(src, dst)
  File "/space/TMP/crap/python-json-patch/jsonpatch.py", line 322, in from_diff
    return cls(list(compare_values([], src, dst)))
  File "/space/TMP/crap/python-json-patch/jsonpatch.py", line 297, in compare_values
    for operation in compare_lists(path, value, other):
  File "/space/TMP/crap/python-json-patch/jsonpatch.py", line 730, in _optimize
    for item in operations:
  File "/space/TMP/crap/python-json-patch/jsonpatch.py", line 649, in _compare
    for op, _ in _compare_with_shift(path, src, dst, left, right, 0):
  File "/space/TMP/crap/python-json-patch/jsonpatch.py", line 672, in _compare_with_shift
    shift=shift):
  File "/space/TMP/crap/python-json-patch/jsonpatch.py", line 672, in _compare_with_shift
    shift=shift):
  File "/space/TMP/crap/python-json-patch/jsonpatch.py", line 675, in _compare_with_shift
    for item, shift in _compare_right(path, dst, right, shift):
  File "/space/TMP/crap/python-json-patch/jsonpatch.py", line 710, in _compare_right
    {'op': 'add', 'path': ptr.path, 'value': dst[idx]},
IndexError: list index out of range
```

If we look at the output of `_split_by_common_seq`
```
>>> jsonpatch._split_by_common_seq(src, dest)
[[(0, 1), None], [[(8, 9), None], [None, (9, 11)]]]
```
That (9, 11) is causing the issue, as dest is only 10 items long.

It looks like it's made this tree, which is valid.
```
[7, 2, 1, 0, 9, 4, 3]
   /   \
[8]     [6]
        / \
     [5]   [5, 8]
```
Based on that, the last tuple shuld be `(8, 10)`, which would work.

I've been staring at this and I can't work it out. I think it's something in the way the indexes are added together when recursing, but my brain can never handle logic to do with list indices.

Any suggestions would be great as it turns out this pattern of Array appears frequently in the data I'm dealing with.

**Comment by jcrosen** [comment]
+1   We just ran into this issue as well when creating patches with an object structured similar to:

```python
{
    'list': [
        {'sub-list': [{...}, {...}, ...]},
        # ...
    ]
}
```

Changing entries in either of the lists in the example above could generate an `IndexError`.  I believe @neoshrew's example accurately illustrates the same issue we encountered.

**Comment by apinkney97** [comment]
Smaller example, Python 2.7.6, jsonpatch 1.11:

```python
import jsonpatch
src = [1, 2, 3, 4]
dest = [2, 3, 5, 4, 6]
jsonpatch.make_patch(src, dest)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/jsonpatch.py", line 171, in make_patch
    return JsonPatch.from_diff(src, dst)
  File "build/bdist.linux-x86_64/egg/jsonpatch.py", line 322, in from_diff
    return cls(list(compare_values([], src, dst)))
  File "build/bdist.linux-x86_64/egg/jsonpatch.py", line 297, in compare_values
    for operation in compare_lists(path, value, other):
  File "build/bdist.linux-x86_64/egg/jsonpatch.py", line 730, in _optimize
    for item in operations:
  File "build/bdist.linux-x86_64/egg/jsonpatch.py", line 649, in _compare
    for op, _ in _compare_with_shift(path, src, dst, left, right, 0):
  File "build/bdist.linux-x86_64/egg/jsonpatch.py", line 672, in _compare_with_shift
    shift=shift):
  File "build/bdist.linux-x86_64/egg/jsonpatch.py", line 672, in _compare_with_shift
    shift=shift):
  File "build/bdist.linux-x86_64/egg/jsonpatch.py", line 675, in _compare_with_shift
    for item, shift in _compare_right(path, dst, right, shift):
  File "build/bdist.linux-x86_64/egg/jsonpatch.py", line 710, in _compare_right
    {'op': 'add', 'path': ptr.path, 'value': dst[idx]},
IndexError: list index out of range
```
