### ISSUE TITLE
Can't install with pyenv virtualenv on OS X: UnicodeDecodeError 

### ISSUE THREAD

**Issue by audiodude** [stefankoegl/python-json-patch#42]
Using a pyenv virtualenv on OS X 10.9 with python 3.4.2.

The install command was `pip install -r requirements.txt` for a project that has dependencies on jsonpatch.

This is what's in the install log:
```
  Downloading jsonpatch-0.4.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/j/jsonpatch/jsonpatch-0.4.tar.gz#md5=81b31ded626e6c15b4cc8b8f094e9490 (from https://pypi.python.org/simple/jsonpatch/)
  Running setup.py (path:/Users/tmoney/.pyenv/versions/inspectors-general/build/jsonpatch/setup.py) egg_info for package jsonpatch
Downloading/unpacking jsonpatch==0.4 (from internetarchive->-r requirements.txt (line 10))
  Downloading jsonpatch-0.4.tar.gz
  Running setup.py (path:/Users/tmoney/.pyenv/versions/inspectors-general/build/jsonpatch/setup.py) egg_info for package jsonpatch
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/tmoney/.pyenv/versions/inspectors-general/build/jsonpatch/setup.py", line 13, in <module>
        src = open('jsonpatch.py').read()
      File "/Users/tmoney/.pyenv/versions/3.4.2/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 173: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/tmoney/.pyenv/versions/inspectors-general/build/jsonpatch/setup.py", line 13, in <module>

    src = open('jsonpatch.py').read()

  File "/Users/tmoney/.pyenv/versions/3.4.2/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 173: ordinal not in range(128)
```

**Comment by stefankoegl** [comment]
This project seems to depend on version 0.4 which was released in July 2012. In recent versions this problem should not occur anymore.

Please ask the project to update to a more recent version of jsonpatch.
