### ISSUE TITLE
Cannot make a reverse patch (test 'Add into composite value')

### ISSUE THREAD

**Issue by ukch** [stefankoegl/python-json-patch#48]
In my code, I am taking a patch, applying it, then creating a reverse patch so I can revert the changes in future should I wish (sort of like a very simple VCS). I am using the [tests.json](https://github.com/json-patch/json-patch-tests/blob/master/tests.json) file to test my own code, and it is failing the test 'Add into composite value'.

Here is a simplified example of the code that is failing:

``` python
import jsonpatch
test = {
    "comment": "Add into composite value",
    "doc": {"foo": 1, "baz": [{"qux": "hello"}]},
    "patch": [{"op": "add", "path": "/baz/0/foo", "value": "world"}],
    "expected": {"foo": 1, "baz": [{"qux": "hello", "foo": "world"}]}
}
patch = jsonpatch.JsonPatch(test["patch"])
new_doc = patch.apply(test["doc"])
assert new_doc == test["expected"]
reverse_patch = jsonpatch.make_patch(new_doc, test["doc"])
# do something with reverse_patch
```

And here is the traceback I am getting:

``` python-traceback
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    reverse_patch = jsonpatch.make_patch(new_doc, test["doc"])
  File "$VIRTUAL_ENV/lib/python3.5/site-packages/jsonpatch.py", line 171, in make_patch
    return JsonPatch.from_diff(src, dst)
  File "$VIRTUAL_ENV/lib/python3.5/site-packages/jsonpatch.py", line 322, in from_diff
    return cls(list(compare_values([], src, dst)))
  File "$VIRTUAL_ENV/lib/python3.5/site-packages/jsonpatch.py", line 293, in compare_values
    for operation in compare_dicts(path, value, other):
  File "$VIRTUAL_ENV/lib/python3.5/site-packages/jsonpatch.py", line 310, in compare_dicts
    for operation in compare_values(current, src[key], dst[key]):
  File "$VIRTUAL_ENV/lib/python3.5/site-packages/jsonpatch.py", line 297, in compare_values
    for operation in compare_lists(path, value, other):
  File "$VIRTUAL_ENV/lib/python3.5/site-packages/jsonpatch.py", line 739, in _optimize
    _optimize_using_replace(ops_by_path[item['path']], item)
  File "$VIRTUAL_ENV/lib/python3.5/site-packages/jsonpatch.py", line 772, in _optimize_using_replace
    prev['value'] = patch.patch[0]['value']
KeyError: 'value'
```

**Comment by langma** [comment]
I'm seeing the exact same error, but I'm making a simple patch. The files are huge so I haven't (yet) tried to find out what could be the reason.

Anyway, I'm getting this error with version 1.13, but with version 1.11 the patch is generated without a problem.

**Comment by stefankoegl** [comment]
I cannot reproduce that with 1.15 anymore, so I assume it has been fixed already. Please let me know if the issue still persists for you.
