### ISSUE TITLE
:q

### ISSUE THREAD

**Issue by symroe** [stefankoegl/python-json-patch#91]

**Comment by rmb938** [comment]
I am having the same issue, using the example in the docs

```
Python 3.6.6
```

```
import jsonpatch
src = {'foo': 'bar', 'numbers': [1, 3, 4, 8]}
dst = {'baz': 'qux', 'numbers': [1, 4, 7]}
patch = jsonpatch.make_patch(src, dst)
result = patch.apply(doc)

Traceback (most recent call last):
  File "/home/rbelgrave/.local/share/virtualenvs/test-RQFjY04W/lib/python3.6/site-packages/jsonpatch.py", line 385, in apply
    del subobj[part]
KeyError: 'foo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rbelgrave/.local/share/virtualenvs/test-RQFjY04W/lib/python3.6/site-packages/jsonpatch.py", line 312, in apply
    obj = operation.apply(obj)
  File "/home/rbelgrave/.local/share/virtualenvs/test-RQFjY04W/lib/python3.6/site-packages/jsonpatch.py", line 388, in apply
    raise JsonPatchConflict(msg)
jsonpatch.JsonPatchConflict: can't remove non-existent object 'foo'
```
